name: Web-Ext lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: web-ext lint
        uses: freaktechnik/web-ext-lint@v1
        with:
          extension-root: "src"

